# Generated by Django 3.0.4 on 2020-03-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('start_time', models.DateTimeField(verbose_name='start of appointment')),
                ('end_time', models.DateTimeField(verbose_name='end of appointment')),
                ('room_name', models.CharField(max_length=255)),
                ('staffmember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.StaffMember')),
            ],
        ),
    ]
