# Generated by Django 3.0.4 on 2020-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='end of appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start of appointment'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
