# Generated by Django 3.0.4 on 2020-03-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200324_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end of appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staffmember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.StaffMember'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start of appointment'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
