# Generated by Django 3.0.4 on 2020-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200324_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
