# Generated by Django 3.0.4 on 2020-03-27 14:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_staffmember_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='name',
            field=models.CharField(help_text='Full name', max_length=255),
        ),
    ]
